export enum EBookActionTypes {
  INIT = '[BOOK] Book init',
  FETCH_BOOK_INFO = '[BOOK] Fetch book info',
  FETCH_BOOK_INFO_SUCCESS = '[BOOK] Fetch book info success',
  FETCH_BOOK_INFO_FAIL = '[BOOK] Fetch book info fail',
  FETCH_BOOK_STATUS = '[BOOK] Fetch book status',
  FETCH_BOOK_STATUS_SUCCESS = '[BOOK] Fetch book status success',
  FETCH_BOOK_STATUS_FAIL = '[BOOK] Fetch book status fail',
  VIEW_BOOK = '[BOOK] View book',
  VIEW_BOOK_SUCCESS = '[BOOK] View book success',
  VIEW_BOOK_FAIL = '[BOOK] View book fail',
  REQUEST_BOOK = '[BOOK] Request book',
  REQUEST_BOOK_SUCCESS = '[BOOK] Request book success',
  REQUEST_BOOK_FAIL = '[BOOK] Request book fail',
  UPDATE_BOOK = '[BOOK] Update book',
  UPDATE_BOOK_SUCCESS = '[BOOK] Update book success',
  UPDATE_BOOK_FAIL = '[BOOK] Update book fail',
}
