version: "3.9"
services:
  frontend:
    image: ghcr.io/anutre/base-frontend:20.0.0-1
    networks:
      - traefik

  frontend_web:
    restart: always
    hostname: frontend_web
    image: nginx:1.27-alpine
    volumes:
      - ./docker/nginx/config/conf.d:/etc/nginx/conf.d
    sysctls:
      net.core.somaxconn: 65536
      net.ipv4.tcp_syncookies: 0
      net.ipv4.tcp_fin_timeout: 10
      net.ipv4.tcp_synack_retries: 1
      net.ipv4.tcp_keepalive_time: 60
      net.ipv4.ip_local_port_range: "1200 65000"
      net.ipv6.conf.all.disable_ipv6: 1
      net.ipv6.conf.default.disable_ipv6: 1
      net.ipv6.conf.lo.disable_ipv6: 1
      net.ipv6.conf.eth0.disable_ipv6: 1
    networks:
      - traefik
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - frontend

networks:
  traefik:
    external:
      name: traefik-proxy

