export enum EAuthActionTypes {
  INIT = '[Auth] Auth Init',
  LOGIN = '[Auth] Login',
  LOGIN_SUCCESS = '[AUTH] Login Success',
  LOGIN_FAIL = '[AUTH] Login Fail',
  LOGIN_TG = '[Auth] Login with telegram',
  LOGIN_TG_SUCCESS = '[Auth] Login with telegram success',
  LOGIN_TG_FAIL = '[Auth] Login with telegram fail',
  LOGIN_APPLE = '[Auth] Login with apple',
  LOGIN_APPLE_SUCCESS = '[Auth] Login with apple success',
  LOGIN_APPLE_FAIL = '[Auth] Login with apple fail',
  REGISTER = '[Auth] Register',
  REGISTER_SUCCESS = '[AUTH] Register Success',
  REGISTER_FAIL = '[AUTH] Register Fail',
  LOGOUT = '[Auth] Logout',
  LOGOUT_SUCCESS = '[Auth] Logout Success',
  LOGOUT_FAIL = '[Auth] Logout Fail',
  DELETE_ACCOUNT = '[Auth] Delete Account',
  DELETE_ACCOUNT_SUCCESS = '[Auth] Delete Account Success',
  DELETE_ACCOUNT_FAIL = '[Auth] Delete Account Fail',
  SET_TOKENS = '[Auth] Set tokens',
}
