export enum ApiPathConfig {
  me = '/sso/me',
  login = '/sso/login',
  loginTelegram = '/sso/register/telegram',
  loginApple = '/sso/register/apple',
  register = '/sso/register',
  refresh = '/sso/refresh',
  logout = '/sso/logout',
  index = '/index',
  messenger = '/messenger',
  dialogUser = '/user',
  deleteUserAccount = '/user/delete',
  dialogUserSubs = '/subscription',
  booksSearch = '/book/search',
  book = '/book',
  bookUpdate = '/book/edit',
  bookView = '/book/views',
  userBooksAdded = '/user/books/added',
  userBooksViewed = '/user/books/viewed',
  bookRequest = '/request',
  emailConfirmationResubmit = '/verify/resubmit',
  metaCounters = '/meta/counters',
  geolocation = '/geolocation',
}
